// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAimksrK5UGytk700FQ1Igu1xsXDZssM9I',
    appId: '1:421490736698:web:030030ec96b06d7353bf03',
    messagingSenderId: '421490736698',
    projectId: 'finanzapp-4e0a2',
    authDomain: 'finanzapp-4e0a2.firebaseapp.com',
    storageBucket: 'finanzapp-4e0a2.appspot.com',
    measurementId: 'G-JL22L88C47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4eS5DEpVUAU0gyjds1KAf8ZbY53UWAnE',
    appId: '1:421490736698:android:92cd3628a6cc34c653bf03',
    messagingSenderId: '421490736698',
    projectId: 'finanzapp-4e0a2',
    storageBucket: 'finanzapp-4e0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaqplJLAEFCt7Kdd_LbtgWMzaJlWFIFjc',
    appId: '1:421490736698:ios:6d0eef91d0f36d9853bf03',
    messagingSenderId: '421490736698',
    projectId: 'finanzapp-4e0a2',
    storageBucket: 'finanzapp-4e0a2.appspot.com',
    iosBundleId: 'com.example.frontProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaqplJLAEFCt7Kdd_LbtgWMzaJlWFIFjc',
    appId: '1:421490736698:ios:6d0eef91d0f36d9853bf03',
    messagingSenderId: '421490736698',
    projectId: 'finanzapp-4e0a2',
    storageBucket: 'finanzapp-4e0a2.appspot.com',
    iosBundleId: 'com.example.frontProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAimksrK5UGytk700FQ1Igu1xsXDZssM9I',
    appId: '1:421490736698:web:a47828985227b2e853bf03',
    messagingSenderId: '421490736698',
    projectId: 'finanzapp-4e0a2',
    authDomain: 'finanzapp-4e0a2.firebaseapp.com',
    storageBucket: 'finanzapp-4e0a2.appspot.com',
    measurementId: 'G-34QJ4KKHF0',
  );

}